package com.bawi.drools

import com.bawi.drools.order.domain.*
import java.math.BigDecimal;

global com.bawi.drools.order.actions.CountryAndQuantityDiscountAction countryAndQuantityDiscountAction

dialect "mvel"

rule "Should apply discount for Poland"
    when
        orderRQ : OrderRQ()
        // address : Address(country in ("Poland")) // also ok
        address : Address(isCountryInListCaseNotSensitive(["Poland"]))
        $product : Product(quantity >= 4)
    then
        System.out.println("Executing rule action for " + address + " and " + $product);
        countryAndQuantityDiscountAction.applyDiscount(orderRQ, $product, "0.1");
end

