package com.bawi.drools

import com.bawi.drools.order.*
import java.math.BigDecimal;

global com.bawi.drools.order.CountryDiscountAction countryDiscountAction

dialect "mvel"

rule "Should apply discount for Poland"
    when
        orderRQ : OrderRQ()
        address : Address(country in ("Poland"))
        $product : Product(quantity >= 4)
    then
        System.out.println("Executing rule action for " + address + " and " + $product);
        countryDiscountAction.applyDiscount(orderRQ, $product, "0.1");
end

