//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.25 at 07:57:21 PM CET 
//

package com.bawi.services.calculator.model;

import static org.apache.commons.collections.CollectionUtils.isEmpty;

import javax.xml.bind.annotation.XmlRootElement;

import org.apache.log4j.Logger;

import com.bawi.services.calculator.exception.InvalidRequestException;

@XmlRootElement(name = "CalculatorRQ")
public class CalculatorRQ extends CalculatorRQModelBase {

	private static Logger logger = Logger.getLogger(CalculatorRQ.class);

	public void validate() throws InvalidRequestException {
		if (operation == null) {
			String message = "Invalid request: operation cannot be null";
			logger.error(message);
			throw new InvalidRequestException(message);
		}
		if (isEmpty(parameters)) {
			String message = "Invalid request: parameters cannot be empty "
					+ parameters;
			logger.error(message);
			throw new InvalidRequestException(message);
		}
	}

}
