-- optional schema.sql (if not present then Spring will generate the schema by default from JPA annotations)
create table shop (
    id bigint generated by default as identity (start with 1),
    shipment_address varchar(255) not null,
    primary key (id)
);
create table product (
    id bigint generated by default as identity (start with 1),
    name varchar(255),
    price numeric(19,2),
    shop_id bigint,
    primary key (id)
);
alter table product
    add constraint FK_4tyglxjor0cq9epm1cqj3j0k6
    foreign key (shop_id)
    references shop;
